serve:
  cookies:
    same_site_mode: Lax
    domain: "demo.io"
    names:
      consent_csrf: "demo_consent_csrf"
      session: "demo_session"
      login_csrf: "demo_login_csrf"
  tls:
    enable: false

urls:
  consent: https://login.demo.io/consent
  login: https://login.demo.io/login
  logout: https://login.demo.io/logout
  error: https://login.demo.io/error
  self:
    issuer: https://openid.demo.io/
    public: https://openid.demo.io/
    admin: https://openid-admin.demo.io/

secrets:
  system:
    - 15744a41-4be9-4ffe-9935-a7b42ce39378

webfinger:
  oidc_discovery:
    supported_claims:
      - name
      - email
      - username
      - userinfo
    supported_scope:
      - profile

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: 15744a41-4be9-4ffe-9935-a7b42ce39378